# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: netscaler 0.8.2 ruby lib

Gem::Specification.new do |s|
  s.name = "netscaler".freeze
  s.version = "0.8.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jeremy Custenborder".freeze, "David Andrew".freeze, "Jarrett Irons".freeze]
  s.date = "2017-05-22"
  s.description = "Netscaler api working against the Citrix Nitro api.  Currently supports Nitro 9.3.  Hope to add support for 10.X.  Currently has support for som basics such as adding servers/services/servicegroups.".freeze
  s.email = ["jeremy@scarcemedia.com".freeze, "david.andrew@webtrends.com".freeze, "jarrett.irons@gmail.com".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/netscaler.rb",
    "lib/netscaler/adapter.rb",
    "lib/netscaler/connection.rb",
    "lib/netscaler/cs.rb",
    "lib/netscaler/cs/policy.rb",
    "lib/netscaler/cs/policylabel.rb",
    "lib/netscaler/cs/vserver.rb",
    "lib/netscaler/cs/vserver/bind.rb",
    "lib/netscaler/cs/vserver/unbind.rb",
    "lib/netscaler/ha.rb",
    "lib/netscaler/ha/node.rb",
    "lib/netscaler/http_adapter.rb",
    "lib/netscaler/lb.rb",
    "lib/netscaler/lb/monitor.rb",
    "lib/netscaler/lb/vserver.rb",
    "lib/netscaler/lb/vserver/bind.rb",
    "lib/netscaler/lb/vserver/unbind.rb",
    "lib/netscaler/load_balancing.rb",
    "lib/netscaler/mock_adapter.rb",
    "lib/netscaler/monkey_patches.rb",
    "lib/netscaler/netscaler_service.rb",
    "lib/netscaler/policy.rb",
    "lib/netscaler/policy/stringmap.rb",
    "lib/netscaler/responder.rb",
    "lib/netscaler/responder/action.rb",
    "lib/netscaler/responder/policy.rb",
    "lib/netscaler/rewrite.rb",
    "lib/netscaler/rewrite/action.rb",
    "lib/netscaler/rewrite/policy.rb",
    "lib/netscaler/server.rb",
    "lib/netscaler/service.rb",
    "lib/netscaler/servicegroup.rb",
    "lib/netscaler/ssl.rb",
    "lib/netscaler/ssl/certkey.rb",
    "lib/netscaler/ssl/vserver.rb",
    "lib/netscaler/ssl/vserver/bind.rb",
    "lib/netscaler/ssl/vserver/unbind.rb",
    "lib/netscaler/system.rb",
    "lib/netscaler/system/file.rb",
    "lib/netscaler/system/interface.rb",
    "netscaler.gemspec",
    "spec/cspolicylabel_spec.rb",
    "spec/csvserver_spec.rb",
    "spec/lbvserver_spec.rb",
    "spec/netscaler_spec.rb",
    "spec/policy_stringmap_spec.rb",
    "spec/responder_spec.rb",
    "spec/rewrite_spec.rb",
    "spec/server_spec.rb",
    "spec/service_spec.rb",
    "spec/servicegroup_spec.rb",
    "spec/spec_helper.rb",
    "spec/sslcertkey_spec.rb",
    "spec/sslvserver_spec.rb",
    "spec/systemfile_spec.rb"
  ]
  s.homepage = "http://github.com/GravityLabs/netscaler".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.11".freeze
  s.summary = "Netscaler api working against the Citrix Nitro api.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>.freeze, ["~> 1.6.7.2"])
      s.add_runtime_dependency(%q<rest-client>.freeze, ["~> 2.0"])
      s.add_runtime_dependency(%q<json>.freeze, ["~> 2.0.2"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.2"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 4.2"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.5"])
      s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.10"])
      s.add_development_dependency(%q<simplecov-rcov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>.freeze, ["~> 1.6.7.2"])
      s.add_dependency(%q<rest-client>.freeze, ["~> 2.0"])
      s.add_dependency(%q<json>.freeze, ["~> 2.0.2"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.2"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 4.2"])
      s.add_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.5"])
      s.add_dependency(%q<simplecov>.freeze, ["~> 0.10"])
      s.add_dependency(%q<simplecov-rcov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>.freeze, ["~> 1.6.7.2"])
    s.add_dependency(%q<rest-client>.freeze, ["~> 2.0"])
    s.add_dependency(%q<json>.freeze, ["~> 2.0.2"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.2"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 4.2"])
    s.add_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.5"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0.10"])
    s.add_dependency(%q<simplecov-rcov>.freeze, [">= 0"])
  end
end

