# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: netscaler 0.6.0 ruby lib

Gem::Specification.new do |s|
  s.name = "netscaler"
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jeremy Custenborder", "David Andrew", "Jarrett Irons"]
  s.date = "2015-05-24"
  s.description = "Netscaler api working against the Citrix Nitro api.  Currently supports Nitro 9.3.  Hope to add support for 10.X.  Currently has support for som basics such as adding servers/services/servicegroups."
  s.email = ["jeremy@scarcemedia.com", "david.andrew@webtrends.com", "jarrett.irons@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/netscaler.rb",
    "lib/netscaler/adapter.rb",
    "lib/netscaler/connection.rb",
    "lib/netscaler/cs.rb",
    "lib/netscaler/cs/policy.rb",
    "lib/netscaler/cs/vserver.rb",
    "lib/netscaler/cs/vserver/bind.rb",
    "lib/netscaler/cs/vserver/unbind.rb",
    "lib/netscaler/http_adapter.rb",
    "lib/netscaler/lb.rb",
    "lib/netscaler/lb/monitor.rb",
    "lib/netscaler/lb/vserver.rb",
    "lib/netscaler/lb/vserver/bind.rb",
    "lib/netscaler/lb/vserver/unbind.rb",
    "lib/netscaler/load_balancing.rb",
    "lib/netscaler/mock_adapter.rb",
    "lib/netscaler/monkey_patches.rb",
    "lib/netscaler/netscaler_service.rb",
    "lib/netscaler/policy.rb",
    "lib/netscaler/policy/stringmap.rb",
    "lib/netscaler/responder.rb",
    "lib/netscaler/responder/action.rb",
    "lib/netscaler/responder/policy.rb",
    "lib/netscaler/rewrite.rb",
    "lib/netscaler/rewrite/action.rb",
    "lib/netscaler/rewrite/policy.rb",
    "lib/netscaler/server.rb",
    "lib/netscaler/service.rb",
    "lib/netscaler/servicegroup.rb",
    "lib/netscaler/ssl.rb",
    "lib/netscaler/ssl/vserver.rb",
    "lib/netscaler/ssl/vserver/bind.rb",
    "lib/netscaler/ssl/vserver/unbind.rb",
    "netscaler.gemspec",
    "spec/csvserver_spec.rb",
    "spec/lbvserver_spec.rb",
    "spec/netscaler_spec.rb",
    "spec/policy_stringmap_spec.rb",
    "spec/responder_spec.rb",
    "spec/rewrite_spec.rb",
    "spec/server_spec.rb",
    "spec/service_spec.rb",
    "spec/servicegroup_spec.rb",
    "spec/spec_helper.rb",
    "spec/sslvserver_spec.rb"
  ]
  s.homepage = "http://github.com/GravityLabs/netscaler"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Netscaler api working against the Citrix Nitro api."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.8.0"])
      s.add_runtime_dependency(%q<json>, ["~> 1.8.2"])
      s.add_development_dependency(%q<rspec>, ["~> 3.2"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.10"])
      s.add_development_dependency(%q<simplecov-rcov>, [">= 0"])
    else
      s.add_dependency(%q<rest-client>, ["~> 1.8.0"])
      s.add_dependency(%q<json>, ["~> 1.8.2"])
      s.add_dependency(%q<rspec>, ["~> 3.2"])
      s.add_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, ["~> 0.10"])
      s.add_dependency(%q<simplecov-rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rest-client>, ["~> 1.8.0"])
    s.add_dependency(%q<json>, ["~> 1.8.2"])
    s.add_dependency(%q<rspec>, ["~> 3.2"])
    s.add_dependency(%q<rdoc>, ["~> 4.2"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, ["~> 0.10"])
    s.add_dependency(%q<simplecov-rcov>, [">= 0"])
  end
end

